# Generated by Django 5.2.4 on 2025-09-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteasset',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
