# Generated by Django 5.2.4 on 2025-09-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_siteasset_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('users_label', models.CharField(blank=True, max_length=255, null=True)),
                ('footer_text', models.CharField(blank=True, max_length=255, null=True)),
                ('bg_banner', models.ImageField(blank=True, null=True, upload_to='homepage/')),
                ('banner_user', models.ImageField(blank=True, null=True, upload_to='homepage/')),
                ('vertical_bar', models.ImageField(blank=True, null=True, upload_to='homepage/')),
                ('arrow_icon', models.ImageField(blank=True, null=True, upload_to='homepage/')),
                ('user1', models.ImageField(blank=True, null=True, upload_to='homepage/users/')),
                ('user2', models.ImageField(blank=True, null=True, upload_to='homepage/users/')),
                ('user3', models.ImageField(blank=True, null=True, upload_to='homepage/users/')),
                ('user4', models.ImageField(blank=True, null=True, upload_to='homepage/users/')),
                ('user5', models.ImageField(blank=True, null=True, upload_to='homepage/users/')),
            ],
            options={
                'verbose_name': 'Home Page Content',
                'verbose_name_plural': 'Home Page Content',
            },
        ),
        migrations.RemoveField(
            model_name='siteasset',
            name='text',
        ),
    ]
