# Generated by Django 5.2.5 on 2025-09-02 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_homepagecontent_remove_siteasset_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePageContent',
        ),
    ]
