# Generated by Django 5.2.5 on 2025-09-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_homepagecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Build Confidence With Every Single Trade. Invest for Your Future', max_length=200)),
                ('subtitle', models.CharField(default='Keep Your Money Safe !!!!', max_length=200)),
                ('description', models.CharField(default='Your Trading Journey Started Here….', max_length=250)),
                ('bg_banner', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('banner_user', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('vertical_bar', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('arrow', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('user1', models.ImageField(blank=True, null=True, upload_to='home/users/')),
                ('user2', models.ImageField(blank=True, null=True, upload_to='home/users/')),
                ('user3', models.ImageField(blank=True, null=True, upload_to='home/users/')),
                ('user4', models.ImageField(blank=True, null=True, upload_to='home/users/')),
                ('user5', models.ImageField(blank=True, null=True, upload_to='home/users/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
