# Generated by Django 5.2.5 on 2025-09-02 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_homesection1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeSection1',
            new_name='HomeSection',
        ),
    ]
