# Generated by Django 5.2.5 on 2025-09-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_homesection1_homesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, help_text='Main description text for section 2', null=True)),
                ('image', models.ImageField(blank=True, help_text='Upload right-side phone/chart image', null=True, upload_to='homepage/')),
            ],
        ),
    ]
