# Generated by Django 5.2.5 on 2025-09-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_homesection2'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('highlight', models.BooleanField(default=False)),
            ],
        ),
    ]
