# Generated by Django 5.2.5 on 2025-09-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_homesection3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homesection2',
            name='text',
        ),
        migrations.AddField(
            model_name='homesection2',
            name='paragraph1',
            field=models.TextField(blank=True, help_text='First paragraph', null=True),
        ),
        migrations.AddField(
            model_name='homesection2',
            name='paragraph2',
            field=models.TextField(blank=True, help_text='Second highlighted paragraph', null=True),
        ),
        migrations.AddField(
            model_name='homesection2',
            name='paragraph3',
            field=models.TextField(blank=True, help_text='Third paragraph', null=True),
        ),
        migrations.AlterField(
            model_name='homesection2',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/'),
        ),
        migrations.AlterField(
            model_name='homesection3',
            name='highlight',
            field=models.BooleanField(default=False, help_text='Highlight this step (green box)'),
        ),
    ]
