# Generated by Django 5.2.5 on 2025-09-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_homesection2_text_homesection2_paragraph1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homesection',
            options={'verbose_name': 'Home Section (Hero)', 'verbose_name_plural': 'Home Section (Hero)'},
        ),
        migrations.AlterModelOptions(
            name='homesection2',
            options={'verbose_name': 'Home Section 2', 'verbose_name_plural': 'Home Section 2'},
        ),
        migrations.AlterModelOptions(
            name='homesection3',
            options={'ordering': ['step_number'], 'verbose_name': 'Home Section 3 Step', 'verbose_name_plural': 'Home Section 3 Steps'},
        ),
        migrations.AlterField(
            model_name='homesection2',
            name='paragraph1',
            field=models.TextField(blank=True, help_text='First paragraph (normal text)', null=True),
        ),
        migrations.AlterField(
            model_name='homesection2',
            name='paragraph2',
            field=models.TextField(blank=True, help_text='Second paragraph (highlighted in green)', null=True),
        ),
        migrations.AlterField(
            model_name='homesection2',
            name='paragraph3',
            field=models.TextField(blank=True, help_text='Third paragraph (footer text)', null=True),
        ),
        migrations.AlterField(
            model_name='homesection3',
            name='highlight',
            field=models.BooleanField(default=False, help_text='Mark this step as highlighted (green middle box)'),
        ),
        migrations.AlterField(
            model_name='homesection3',
            name='step_number',
            field=models.CharField(help_text='Step number like 01, 02, 03', max_length=5),
        ),
    ]
