# Generated by Django 5.2.5 on 2025-09-02 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_homesection_options_alter_homesection2_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to='about/banner/')),
                ('banner_title', models.CharField(default='About TRACO', max_length=200)),
                ('who_title', models.CharField(default='Who are We?', max_length=200)),
                ('who_para1', models.TextField(blank=True, null=True)),
                ('who_para2', models.TextField(blank=True, null=True)),
                ('mission_title', models.CharField(default='Our Mission', max_length=200)),
                ('mission_text', models.TextField(blank=True, null=True)),
                ('mission_image', models.ImageField(blank=True, null=True, upload_to='about/mission/')),
                ('vision_title', models.CharField(default='Our Vision', max_length=200)),
                ('vision_text', models.TextField(blank=True, null=True)),
                ('vision_image', models.ImageField(blank=True, null=True, upload_to='about/vision/')),
            ],
        ),
        migrations.CreateModel(
            name='WhyChooseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='about/why_icons/')),
                ('title', models.CharField(max_length=200)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_items', to='accounts.aboutcontent')),
            ],
        ),
    ]
