# Generated by Django 5.2.5 on 2025-09-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_aboutcontent_whychooseitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='home/section4/')),
                ('highlight', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
    ]
