# Generated by Django 5.2.5 on 2025-09-02 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_homesection4'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeSection4',
        ),
    ]
