# Generated by Django 5.2.5 on 2025-09-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_delete_homesection4'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='How it Works?', max_length=200)),
                ('apply_title', models.CharField(default='Apply', max_length=100)),
                ('apply_desc', models.TextField(default='Join thousands of traders who trust our platform every day.')),
                ('apply_img', models.ImageField(blank=True, null=True, upload_to='section4/')),
                ('assess_title', models.CharField(default='Assessment', max_length=100)),
                ('assess_desc', models.TextField(default='Take our short assessment to discover your trading style, risk tolerance, and the tools that fit you best.')),
                ('assess_img', models.ImageField(blank=True, null=True, upload_to='section4/')),
                ('fund_title', models.CharField(default='Get Funded', max_length=100)),
                ('fund_desc', models.TextField(default='Trade with our capital and keep up to 90% of the profits.')),
                ('fund_img', models.ImageField(blank=True, null=True, upload_to='section4/')),
                ('trade_title', models.CharField(default='Trade & Grow', max_length=100)),
                ('trade_desc', models.TextField(default="Whether you're just starting or scaling up, our tools, support, and funding help you grow with confidence.")),
                ('trade_img', models.ImageField(blank=True, null=True, upload_to='section4/')),
            ],
        ),
    ]
