# Generated by Django 5.2.5 on 2025-09-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_homesection4'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunitySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Build a Strong Community', max_length=200)),
                ('description', models.TextField(default='Join a global network of passionate traders...')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='community/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='community/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='community/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='community/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='community/')),
            ],
        ),
    ]
