# Generated by Django 5.2.5 on 2025-09-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_communitysection'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Welcome to Our Platform', max_length=200)),
                ('subtitle', models.TextField(default='Trade smarter, faster, and with confidence.')),
                ('banner_img', models.ImageField(blank=True, null=True, upload_to='banner/')),
                ('button_text', models.CharField(blank=True, max_length=100, null=True)),
                ('button_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
