# Generated by Django 5.2.5 on 2025-09-03 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_bannersection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannersection',
            name='button_link',
        ),
        migrations.RemoveField(
            model_name='bannersection',
            name='button_text',
        ),
    ]
