# Generated by Django 5.2.5 on 2025-09-03 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_bannersection_button_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannersection',
            name='subtitle',
        ),
    ]
