# Generated by Django 5.2.5 on 2025-09-03 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_bannersection_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Don’t Just Gain info', max_length=200)),
                ('subtitle', models.CharField(default='Build Knowledge', max_length=200)),
                ('description', models.TextField(default='Whether you’re a new investor or a market expert, we’ve got something for everyone at the TRACO blog')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
            ],
        ),
    ]
