# Generated by Django 5.2.5 on 2025-09-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_bloghero'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloghero',
            name='sparkle',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
    ]
