# Generated by Django 5.2.5 on 2025-09-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_bloghero_sparkle'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_key', models.CharField(choices=[('stocks', 'Stocks'), ('mutual', 'Mutual Funds'), ('finance', 'Personal Finance'), ('futures', 'Futures & Options')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
