# Generated by Django 5.2.5 on 2025-09-03 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_blogtab'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('stocks', 'Stocks'), ('mutual', 'Mutual Funds'), ('finance', 'Personal Finance'), ('futures', 'Futures & Options')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('short_desc', models.TextField()),
                ('read_time', models.CharField(default='5 Mins Read', max_length=50)),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_posts/')),
            ],
        ),
        migrations.RemoveField(
            model_name='blogtab',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='blogtab',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
