# Generated by Django 5.2.5 on 2025-09-03 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_blogpost_remove_blogtab_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogtab',
            name='content',
        ),
        migrations.RemoveField(
            model_name='blogtab',
            name='title',
        ),
    ]
