# Generated by Django 5.2.5 on 2025-09-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_remove_blogtab_content_remove_blogtab_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesection',
            name='title1',
            field=models.CharField(default='Invest for Your Future', max_length=200),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='title',
            field=models.CharField(default='Build Confidence With Every Single Trade.', max_length=200),
        ),
    ]
