# Generated by Django 5.2.5 on 2025-09-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_homesection_title1_alter_homesection_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesection2',
            name='image20years',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/'),
        ),
    ]
