# Generated by Django 5.2.5 on 2025-09-03 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_homesection2_image20years'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homesection',
            options={'verbose_name': 'Home Hero_Section', 'verbose_name_plural': 'Home Hero_Section'},
        ),
    ]
