# Generated by Django 5.2.5 on 2025-09-03 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_homesection_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutcontent',
            options={'verbose_name': 'About Section', 'verbose_name_plural': 'About Section'},
        ),
        migrations.AlterModelOptions(
            name='bannersection',
            options={'verbose_name': 'Home Dashboard_Section', 'verbose_name_plural': 'Home Dashbord_Section'},
        ),
        migrations.AlterModelOptions(
            name='communitysection',
            options={'verbose_name': 'Home community_Section', 'verbose_name_plural': 'Home community_Section'},
        ),
        migrations.AlterModelOptions(
            name='homesection2',
            options={'verbose_name': 'Home Section_2', 'verbose_name_plural': 'Home Section_2'},
        ),
        migrations.AlterModelOptions(
            name='homesection3',
            options={'ordering': ['step_number'], 'verbose_name': 'Home Section_3', 'verbose_name_plural': 'Home Section_3'},
        ),
        migrations.AlterModelOptions(
            name='homesection4',
            options={'verbose_name': 'Home Section_4', 'verbose_name_plural': 'Home Section_4'},
        ),
    ]
