# Generated by Django 5.2.5 on 2025-09-03 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_aboutcontent_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloghero',
            options={'verbose_name': 'Blog Hero_Section', 'verbose_name_plural': 'Blog Hero_Section'},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'Blog Posts', 'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.AlterModelOptions(
            name='blogtab',
            options={'verbose_name': 'Blog tabs', 'verbose_name_plural': 'Blog tabs'},
        ),
        migrations.AlterModelOptions(
            name='homesection2',
            options={'verbose_name': 'Home Experience_Section', 'verbose_name_plural': 'Home Experience_Section'},
        ),
        migrations.AlterModelOptions(
            name='homesection3',
            options={'ordering': ['step_number'], 'verbose_name': 'Home Features_Section', 'verbose_name_plural': 'Home Features_Section'},
        ),
        migrations.AlterModelOptions(
            name='homesection4',
            options={'verbose_name': 'Home How_It_Works_Section', 'verbose_name_plural': 'Home How_It_Works_Section'},
        ),
    ]
