# Generated by Django 5.2.5 on 2025-09-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_bloghero_options_alter_blogpost_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesection',
            name='realtime_users_count',
            field=models.CharField(default='500+', max_length=50),
        ),
        migrations.AddField(
            model_name='homesection',
            name='realtime_users_label',
            field=models.CharField(default='Realtime Users', max_length=100),
        ),
    ]
