# Generated by Django 5.2.5 on 2025-09-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_partnerlead'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Welcome to the First Step of Becoming a TRACO Partner', max_length=200)),
                ('sub_text', models.TextField(blank=True, default='Contact us Alternatively, You can Contact Our Business Partner Team', null=True)),
                ('phone', models.CharField(default='022 982231', help_text='Display phone number shown on the partner page', max_length=30)),
                ('email', models.EmailField(default='businesspartner@tranco.in', help_text='Display email shown on the partner page', max_length=254)),
                ('image', models.ImageField(blank=True, help_text='Hero/side image for the partner page', null=True, upload_to='partner/')),
            ],
            options={
                'verbose_name': 'Partner Page Content',
                'verbose_name_plural': 'Partner Page Content',
            },
        ),
    ]
