# Generated by Django 5.2.5 on 2025-09-04 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_partnersection'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerBenefitsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_line1', models.CharField(default='People become partners to earn passive income and grow with a trusted brand.', max_length=200)),
                ('heading_line2', models.CharField(default='They get access to high commissions, marketing support, and long-term business potential.', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Partner – Benefits (Section 2)',
                'verbose_name_plural': 'Partner – Benefits (Section 2)',
            },
        ),
        migrations.CreateModel(
            name='PartnerBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='partner/benefit_icons/')),
                ('order', models.PositiveIntegerField(default=1)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.partnerbenefitssection')),
            ],
            options={
                'verbose_name': 'Partner Benefit Item',
                'verbose_name_plural': 'Partner Benefit Items',
                'ordering': ['order'],
            },
        ),
    ]
