# Generated by Django 5.2.5 on 2025-09-04 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_faqcategory_faq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.DeleteModel(
            name='FAQCategory',
        ),
    ]
