# Generated by Django 5.2.5 on 2025-09-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_delete_faq_delete_faqcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField(help_text='You can use plain text or HTML here.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide from public FAQ page')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('order', '-created'),
            },
        ),
    ]
