# Generated by Django 5.2.5 on 2025-09-04 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_delete_faq'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField(blank=True, help_text='Admin: enter the answer here.')),
                ('is_active', models.BooleanField(default=False, help_text='Published on public FAQ page when checked')),
                ('is_answered', models.BooleanField(default=False, help_text='Checked when admin has answered this question')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_faqs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('order', '-created'),
            },
        ),
    ]
