# Generated by Django 5.2.5 on 2025-09-04 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_faq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
