# Generated by Django 5.2.5 on 2025-09-05 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_accountchart_metriccard_sidewidget_dashboardprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountChart',
        ),
        migrations.RemoveField(
            model_name='dashboardprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='MetricCard',
        ),
        migrations.DeleteModel(
            name='SideWidget',
        ),
        migrations.DeleteModel(
            name='DashboardProfile',
        ),
    ]
