# Generated by Django 5.2.5 on 2025-09-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_delete_accountchart_remove_dashboardprofile_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Main Dashboard', max_length=200)),
                ('kpis', models.JSONField(blank=True, default=list)),
                ('chart', models.JSONField(blank=True, default=dict)),
                ('right_widgets', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
