# Generated by Django 5.2.5 on 2025-09-05 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_dashboardcontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DashboardContent',
        ),
    ]
