# Generated by Django 5.2.5 on 2025-09-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_delete_dashboardcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeInvestorPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='investor/hero/')),
                ('content', models.TextField(help_text='Main HTML or plain text content')),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trade / Investor Page',
                'verbose_name_plural': 'Trade / Investor Pages',
                'ordering': ['-created_at'],
            },
        ),
    ]
