# Generated by Django 5.2.5 on 2025-09-06 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_tradeinvestorpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Press Kit', max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('overview', models.TextField(blank=True)),
                ('media_text', models.TextField(blank=True, help_text='Short description about downloads')),
                ('brand_guide', models.FileField(blank=True, help_text='Upload PDF brand guide (PDF recommended)', null=True, upload_to='press/')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Press Kit',
                'verbose_name_plural': 'Press Kit',
            },
        ),
        migrations.DeleteModel(
            name='TradeInvestorPage',
        ),
    ]
