# Generated by Django 5.2.5 on 2025-09-06 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_presskit_delete_tradeinvestorpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Investor Relations', max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('mission', models.TextField(blank=True)),
                ('highlights', models.TextField(blank=True, help_text='Enter key highlights, one per line.')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Investor Page',
                'verbose_name_plural': 'Investor Page',
            },
        ),
    ]
