# Generated by Django 5.2.5 on 2025-09-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_investorpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Explore Markets', max_length=200)),
                ('subtitle', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Market Explore HeroSection',
                'verbose_name_plural': 'Market Explore HeroSection',
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('short_desc', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='market_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Market Explore Section',
                'verbose_name_plural': 'Market Explore Section',
            },
        ),
    ]
